M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 12:05:45 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T12:05:45-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.9055Y-2.6945
X6.1733Y-2.1579
X6.3888Y-3.2888
X6.9Y-3.2
X6.9112Y-3.3888
X7.1Y-3.3
T2
X5.6Y-3.1
X5.8Y-3.1
T0
M30
